name=input("enter a name:")
print("length of the name is:",len(name))
print("find the variable:",name.find("z"))
print("the capital of the name is:",name.capitalize())
print("upper case of the name is:",name.upper())
print("lower cae of the name is:",name.lower())
print("check wether a given name is digit:",name.isdigit())
print("check the albhabet:",name.isalpha())
print("replace the name:",name.replace("shazeb","juhair"))
print("count the size of name:",name.count(name))
print("repeat the name:",name*5)
print("the index of the name is:",name[2])
print("access the last element:",name[-4])
print("access the character from third index ti fifth index:",name[3:5])
