import numpy as np
array1=np.array([[1,4],[2,3]])
print("The first array is:")
print(array1)
array2=np.array([[2,3],[3,8]])
print("The second array is:")
print(array2)
print("\n adding two arrays")
print(np.add(array1,array2))
print("\n subtracting two arrays:")
print(np.subtract(array1,array2))
print("\n Multiplying two arrays:")
print(np.multiply(array1,array2))
print("\n Dividing two arrays:")
print(np.divide(array1,array2))
print("\n largest element is:",array1.max())
print("\n Row wise maximum elements:",array1.max(axis=1))
print("\n Smallest element is:",array2.min())
print("\n Column wise minimum element",array2.min(axis=1))
print("\n Sum of all array elements:",array1.sum())
print("\n Cumulative sum along each row:",array2.cumsum(axis=1))

